# -*- coding: utf-8 -*-
"""Face RecognitionCV.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HtEeynqDIjTZyZnqWEjsf0IDu2GO3HBl
"""

import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.datasets import cifar10
import cv2

# Load the dataset
npz_path = "/content/yale-face-database.npz"  # Update this path to your file
data = np.load(npz_path)

# Inspect the contents
print("Keys in the .npz file:", data.files)

# Assuming the dataset contains 'images' and 'labels'
images = data['arr_0']  # Replace with the correct key for images if different
labels = data['arr_1']  # Replace with the correct key for labels if different

# Print shapes of images and labels
print(f"Images shape: {images.shape}")
print(f"Labels shape: {labels.shape}")

# Assuming 'images' contains the original images array
# Convert images to grayscale if they are in RGB format
if len(images.shape) == 4 and images.shape[-1] == 3:  # If images are RGB
    images = np.mean(images, axis=-1)  # Convert to grayscale

# Flatten each image without resizing
flattened_images = images.reshape(images.shape[0], -1)  # Shape: (N, H*W)

# Print the shape of the flattened dataset
print(f"Flattened images shape: {flattened_images.shape}")  # Should be (105, 25600)

import matplotlib.pyplot as plt

# Assuming 'images' contains the original images array
# Check if images are already in grayscale
if len(images.shape) == 4 and images.shape[-1] == 3:  # If images are RGB
    images = np.mean(images, axis=-1)  # Convert to grayscale

# Visualize all images in the dataset
num_images = images.shape[0]
plt.figure(figsize=(15, 15))

# Adjust grid size to fit all images
cols = 10  # Number of columns for visualization
rows = (num_images // cols) + (num_images % cols > 0)

for i in range(num_images):
    plt.subplot(rows, cols, i + 1)
    plt.imshow(images[i], cmap='gray')
    plt.title(f"Image {i + 1}")
    plt.axis('off')

plt.tight_layout()
plt.show()

# Step 1: Compute the mean face
mean_face = np.mean(flattened_images, axis=0)  # Mean of each pixel across all images

# Visualize the mean face
plt.figure(figsize=(6, 6))
plt.imshow(mean_face.reshape(160, 160), cmap='gray')  # Reshape back to 2D
plt.title("Mean Face")
plt.axis('off')
plt.show()

# Print shape of the mean face
print(f"Shape of mean face: {mean_face.shape}")

"""The below  code performs mean-centering, a crucial preprocessing step in many machine learning and data analysis tasks, including Principal Component Analysis (PCA). The goal of mean-centering is to shift the data so that its mean becomes zero. This ensures that subsequent analyses focus on the variations in the data rather than the absolute values.


"""

# Step 2: Mean-center the data
mean_centered_data = flattened_images - mean_face

# Verify the mean of the mean-centered data (should be close to zero)
mean_of_centered_data = np.mean(mean_centered_data)
print(f"Mean of mean-centered data: {mean_of_centered_data:.5f}")

mean_of_centered_data = np.mean(mean_centered_data)
print(f"Exact mean of mean-centered data: {mean_of_centered_data:.15f}")

# Step 3: Compute the smaller covariance matrix (N x N)
N = mean_centered_data.shape[0]  # Number of images
small_cov_matrix = np.dot(mean_centered_data, mean_centered_data.T) / N  # Smaller covariance matrix

# Step 4: Perform eigenvalue decomposition on the smaller covariance matrix
small_eigenvalues, small_eigenvectors = np.linalg.eigh(small_cov_matrix)

# Step 5: Map eigenvectors back to the original space
eigenvectors = np.dot(mean_centered_data.T, small_eigenvectors)  # Map to original space
eigenvectors = eigenvectors / np.linalg.norm(eigenvectors, axis=0)  # Normalize

# Step 6: Sort eigenvalues and eigenvectors
sorted_indices = np.argsort(-small_eigenvalues)  # Sort eigenvalues in descending order
eigenvalues = small_eigenvalues[sorted_indices]
eigenvectors = eigenvectors[:, sorted_indices]

# Print the shape of eigenvalues and eigenvectors
print(f"Shape of eigenvalues: {eigenvalues.shape}")
print(f"Shape of eigenvectors: {eigenvectors.shape}")

# Visualize the first 10 Eigenfaces
plt.figure(figsize=(15, 10))
for i in range(10):  # Display top 10 eigenvectors
    eigenface = eigenvectors[:, i].reshape(160, 160)  # Reshape back to 2D
    plt.subplot(2, 5, i + 1)
    plt.imshow(eigenface, cmap='gray')
    plt.title(f"Eigenface {i + 1}")
    plt.axis('off')

plt.tight_layout()
plt.show()

# Visualize all Eigenfaces
num_eigenfaces = eigenvectors.shape[1]  # Total number of eigenvectors
plt.figure(figsize=(15, 15))

# Adjust grid size for visualization
cols = 10  # Number of columns in the grid
rows = (num_eigenfaces // cols) + (num_eigenfaces % cols > 0)

for i in range(num_eigenfaces):
    plt.subplot(rows, cols, i + 1)
    eigenface = eigenvectors[:, i].reshape(160, 160)  # Reshape to original image dimensions
    plt.imshow(eigenface, cmap='gray')
    plt.title(f"Eigenface {i + 1}")
    plt.axis('off')

plt.tight_layout()
plt.show()

from tensorflow.keras.datasets import cifar10
import cv2
import numpy as np

# Step 1: Load CIFAR-10 dataset
(_, _), (cifar_images, cifar_labels) = cifar10.load_data()

# Step 2: Preprocess CIFAR-10 images
# Convert to grayscale and resize to match your face dataset dimensions
cifar_preprocessed = []
for img in cifar_images:
    img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)  # Convert to grayscale
    img_resized = cv2.resize(img_gray, (160, 160))  # Resize to 160x160
    cifar_preprocessed.append(img_resized.flatten())  # Flatten the image

# Convert to NumPy array
cifar_preprocessed = np.array(cifar_preprocessed)
print(f"CIFAR-10 processed images shape: {cifar_preprocessed.shape}")

# Step 1: Assign labels
# Face images (label=1), CIFAR-10 (label=0)
face_labels = np.ones(flattened_images.shape[0])
cifar_labels = np.zeros(cifar_preprocessed.shape[0])

# Step 2: Combine datasets
combined_images = np.vstack((flattened_images, cifar_preprocessed))
combined_labels = np.hstack((face_labels, cifar_labels))

# Print combined dataset shape
print(f"Combined images shape: {combined_images.shape}")
print(f"Combined labels shape: {combined_labels.shape}")

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

# Step 1: Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(combined_images, combined_labels, test_size=0.3, random_state=42)

# Step 2: Train Logistic Regression
clf = LogisticRegression(random_state=42, max_iter=1000)
clf.fit(X_train, y_train)

# Step 3: Predict on the test set
y_pred = clf.predict(X_test)

from sklearn.metrics import classification_report

# Generate classification report
report = classification_report(y_test, y_pred, target_names=["Non-Face", "Face"])
print("Classification Report:")
print(report)

"""Why Such High Performance?
Imbalance in Dataset:

The dataset has significantly more non-face images (2983) compared to face images (49).
Models often perform better on the majority class.

"""